PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX foaf:   <http://xmlns.com/foaf/0.1/>
PREFIX locn:   <http://www.w3.org/ns/locn#>
PREFIX org:    <http://www.w3.org/ns/org#>
PREFIX schema: <http://schema.org/>

CONSTRUCT {
  ?Agent 
    a ?schemaPerson ;
    a ?schemaOrganization ;
    schema:name ?name ;
#    schema:?? ?AgentType ;
    schema:address ?AgentAddress ;
    schema:memberOf ?Affiliation ;
    schema:email ?email ;
    schema:url ?workplaceHomepage ;
    schema:telephone ?phone
} WHERE {
  OPTIONAL { ?Agent a foaf:Agent . }
  OPTIONAL { ?Agent a foaf:Person BIND(schema:Person AS ?schemaPerson) . }
  OPTIONAL { ?Agent a foaf:Organization BIND(schema:Organization AS ?schemaOrganization) . }
  OPTIONAL { ?Agent foaf:name ?name . }
#  OPTIONAL { ?Agent dct:type ?AgentType . }
  OPTIONAL { ?Agent locn:address ?AgentAddress . }
  OPTIONAL { ?Agent org:memberOf ?Affiliation . }
  OPTIONAL { ?Agent foaf:mbox ?email . }
  OPTIONAL { ?Agent foaf:workplaceHomepage ?workplaceHomepage . }
  OPTIONAL { ?Agent foaf:phone ?phone . }
}
