PREFIX adms:   <http://www.w3.org/ns/adms#>
PREFIX schema: <http://schema.org/>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?Identifier 
    schema:propertyID ?identifierType ;
    schema:value ?notation 
} WHERE {
  OPTIONAL { ?Identifier a adms:Identifier . }
  OPTIONAL { ?Identifier skos:notation ?notation . }
  OPTIONAL { ?Identifier skos:notation ?notation bind(str(datatype(?notation)) as ?identifierType) . }
}
