PREFIX dcat:   <http://www.w3.org/ns/dcat#>
PREFIX schema: <http://schema.org/>
PREFIX vcard:  <http://www.w3.org/2006/vcard/ns#>

CONSTRUCT {
  ?Kind a schema:ContactPoint ;
    schema:name ?name ;
    schema:email ?email ;
    schema:address ?KindAddress ;
    schema:memberOf [ a schema:Organization ;
      schema:name ?organisationName 
	] ;
    schema:url ?url ;
    schema:telephone ?telephone 
} WHERE {
  OPTIONAL { ?Resource dcat:contactPoint ?Kind . }
  OPTIONAL { ?Kind a vcard:Kind . }
  OPTIONAL { ?Kind a vcard:Individual . }
  OPTIONAL { ?Kind a vcard:Organization . }
  OPTIONAL { ?Kind vcard:fn ?name . }
  OPTIONAL { ?Kind vcard:hasEmail ?email . }
  OPTIONAL { ?Kind vcard:hasAddress ?KindAddress . }
  OPTIONAL { ?Kind vcard:organization-name ?organisationName . }
  OPTIONAL { ?Kind vcard:hasURL ?url . }
  OPTIONAL { ?Kind vcard:hasTelephone ?telephone . }
}
