PREFIX dcat:   <http://www.w3.org/ns/dcat#>
PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX time:   <http://www.w3.org/2006/time#>
PREFIX schema: <http://schema.org/>

CONSTRUCT {
  ?PeriodOfTime a schema:DateTime ;
    schema:startDate ?startDate ;
    schema:endDate ?endDate ;
    schema:startDate ?hasBeginning ;
    schema:endDate ?hasEnd 
} WHERE {
  OPTIONAL { ?Resource dct:temporal ?PeriodOfTime . }
  OPTIONAL { ?PeriodOfTime a dct:PeriodOfTime . }
  OPTIONAL { ?PeriodOfTime dcat:startDate ?startDate . }
  OPTIONAL { ?PeriodOfTime dcat:endDate ?endDate . }
  OPTIONAL { ?PeriodOfTime time:hasBeginning/(time:inXSDDate|time:inXSDDateTime) ?hasBeginning . }
  OPTIONAL { ?PeriodOfTime time:hasEnd/(time:inXSDDate|time:inXSDDateTime) ?hasEnd . }
}
